name: "Manage GitBoosted Space"
description: "Github action managing GitBoosted Spaces"
author: "GitBoosted"
branding:
  icon: "upload"
  color: "orange"
inputs:
  api_key:
    description: "BASE64 Encoded clientId:clientSecret. Head to https://docs.gitboosted.com to learn how to get your API key."
    required: true
  space_name:
    description: "The name of the space"
    required: true
  repository_name:
    description: "The name of the repository to connect."
    required: false
runs:
  using: "composite"
  steps:
    - name: Send API Call
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://api.gitboosted.com/spaces"
        method: "POST"
        customHeaders: '{"Authorization": "${{ inputs.api_key }}"}'
        data: '{"name": "${{ inputs.space_name }}", "repository": "${{ inputs.repository_name }}"}'
