name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Build and tag a new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Distribute the latest tagged release
        uses: teunmooij/github-versioned-release@v1.2.1
        with:
          template: composite-action
        env:
          GITHUB_TOKEN: ${{ github.token }}
